Document: cvmlcpp
Title: Debian cvmlcpp Manual
Author: <insert document author here>
Abstract: This manual describes what cvmlcpp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cvmlcpp/cvmlcpp.sgml.gz

Format: postscript
Files: /usr/share/doc/cvmlcpp/cvmlcpp.ps.gz

Format: text
Files: /usr/share/doc/cvmlcpp/cvmlcpp.text.gz

Format: HTML
Index: /usr/share/doc/cvmlcpp/html/index.html
Files: /usr/share/doc/cvmlcpp/html/*.html
